services:
  valkey:
    image: valkey/valkey:latest
    container_name: noncesense-valkey
    ports:
      - "6379:6379"
    restart: always

  backend:
    build:
      context: backend/.
      dockerfile: Dockerfile
    container_name: noncesense-backend
    ports:
      - "8000:8000"
    environment:
      - VALKEY_URL=redis://noncesense-valkey:6379/0
      - POW_DIFFICULTY=4
      - CHALLENGE_TTL=120
      - RATE_LIMIT=10 
      - RATE_WINDOW=60
    depends_on:
      - valkey
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    container_name: noncesense-frontend
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
